#!/bin/bash

echo "🔧 Corrigindo Root Directory no Railway"
echo "========================================"
echo ""
echo "O erro 'Could not find root directory: /backend' ocorre porque"
echo "o Railway precisa saber que o root directory é 'backend'."
echo ""
echo "Solução 1: Configurar no Dashboard do Railway"
echo "----------------------------------------------"
echo "1. Acesse: https://railway.app"
echo "2. Vá no seu projeto 'Gerenciador De Tarefas'"
echo "3. Clique no serviço 'gerenciadorTarefa'"
echo "4. Vá em 'Settings'"
echo "5. Em 'Root Directory', defina: backend"
echo "6. Salve as alterações"
echo ""
echo "Solução 2: Re-vincular o projeto a partir do diretório backend"
echo "---------------------------------------------------------------"
echo "Execute estes comandos:"
echo ""
echo "  cd /home/gusgd/Downloads/project-bolt-sb1-7ckdj9rr/project/backend"
echo "  railway unlink"
echo "  railway link"
echo ""
echo "Solução 3: Criar novo serviço apontando para backend"
echo "------------------------------------------------------"
echo "  railway service"
echo "  (selecione ou crie um novo serviço)"
echo ""

