#!/bin/bash

echo "=========================================="
echo "  Recriar Projeto no Railway"
echo "=========================================="
echo ""
echo "📋 PASSO 1: Backup das Variáveis"
echo "----------------------------------------"
railway variables > railway-vars-backup.txt
echo "✅ Variáveis salvas em: railway-vars-backup.txt"
echo ""
echo "📋 PASSO 2: Deletar Serviço Atual"
echo "----------------------------------------"
echo "1. Acesse: https://railway.app/dashboard"
echo "2. Selecione o projeto 'Gerenciador De Tarefas'"
echo "3. Clique no serviço 'gerenciadorTarefa'"
echo "4. Vá em Settings (⚙️)"
echo "5. Role até o final e clique em 'Delete Service'"
echo "6. Confirme a deleção"
echo ""
read -p "Pressione ENTER quando tiver deletado o serviço..."
echo ""
echo "📋 PASSO 3: Criar Novo Serviço"
echo "----------------------------------------"
echo "1. No mesmo projeto, clique em 'New'"
echo "2. Selecione 'GitHub Repo'"
echo "3. Escolha o repositório: flfogaca/gerenciadorTarefa"
echo "4. Configure:"
echo "   - Root Directory: backend"
echo "   - Builder: Dockerfile"
echo ""
read -p "Pressione ENTER quando tiver criado o novo serviço..."
echo ""
echo "📋 PASSO 4: Configurar Variáveis"
echo "----------------------------------------"
echo "1. No novo serviço, vá em Variables"
echo "2. Adicione as variáveis do arquivo railway-vars-backup.txt"
echo ""
echo "Variáveis principais que você precisa:"
echo "- DATABASE_URL (com pooler do Supabase)"
echo "- JWT_SECRET"
echo "- JWT_REFRESH_SECRET"
echo "- ALLOWED_ORIGINS (URL do seu frontend Vercel)"
echo "- E outras variáveis do backup"
echo ""
read -p "Pressione ENTER quando tiver configurado as variáveis..."
echo ""
echo "✅ Pronto! O Railway fará deploy automaticamente."
echo ""
echo "Para acompanhar os logs:"
echo "  railway logs --follow"
echo ""

