// Centralizando todos os tipos para evitar imports circulares
export const TYPES = {
  // Database
  PrismaClient: Symbol.for('PrismaClient'),
  DatabaseService: Symbol.for('DatabaseService'),
  
  // Shared Services
  Logger: Symbol.for('Logger'),
  ValidationService: Symbol.for('ValidationService'),
  
  // Repositories
  TenantRepository: Symbol.for('TenantRepository'),
  UserRepository: Symbol.for('UserRepository'),
  ProjectRepository: Symbol.for('ProjectRepository'),
  TaskRepository: Symbol.for('TaskRepository'),
  ClientRepository: Symbol.for('ClientRepository'),
  SupplierRepository: Symbol.for('SupplierRepository'),
  ExpenseRepository: Symbol.for('ExpenseRepository'),
  InvoiceRepository: Symbol.for('InvoiceRepository'),
  PaymentRepository: Symbol.for('PaymentRepository'),
  FinancialTransactionRepository: Symbol.for('FinancialTransactionRepository'),
  TemplateRepository: Symbol.for('TemplateRepository'),
  UserSettingsRepository: Symbol.for('UserSettingsRepository'),
  TenantSettingsRepository: Symbol.for('TenantSettingsRepository'),
  UnitOfWork: Symbol.for('UnitOfWork'),
  AuditLogRepository: Symbol.for('AuditLogRepository'),
  NotificationRepository: Symbol.for('NotificationRepository'),
  
  // Services
  TenantService: Symbol.for('TenantService'),
  UserService: Symbol.for('UserService'),
  ProjectService: Symbol.for('ProjectService'),
  TaskService: Symbol.for('TaskService'),
  ClientService: Symbol.for('ClientService'),
  SupplierService: Symbol.for('SupplierService'),
  ExpenseService: Symbol.for('ExpenseService'),
  InvoiceService: Symbol.for('InvoiceService'),
  PaymentService: Symbol.for('PaymentService'),
  FinancialTransactionService: Symbol.for('FinancialTransactionService'),
  FinancialReportService: Symbol.for('FinancialReportService'),
  TemplateService: Symbol.for('TemplateService'),
  UserSettingsService: Symbol.for('UserSettingsService'),
  TenantSettingsService: Symbol.for('TenantSettingsService'),
  PermissionService: Symbol.for('PermissionService'),
  NotificationService: Symbol.for('NotificationService'),
  AuditService: Symbol.for('AuditService'),
  CacheService: Symbol.for('CacheService'),
  MonitoringService: Symbol.for('MonitoringService'),
  
  // Use Cases
  CreateTenantUseCase: Symbol.for('CreateTenantUseCase'),
  UpdateTenantUseCase: Symbol.for('UpdateTenantUseCase'),
  GetTenantUseCase: Symbol.for('GetTenantUseCase'),
  ListTenantsUseCase: Symbol.for('ListTenantsUseCase'),
  CreateUserUseCase: Symbol.for('CreateUserUseCase'),
  UpdateUserUseCase: Symbol.for('UpdateUserUseCase'),
  AuthenticateUserUseCase: Symbol.for('AuthenticateUserUseCase'),
  ChangePasswordUseCase: Symbol.for('ChangePasswordUseCase'),
  GetUserUseCase: Symbol.for('GetUserUseCase'),
  ListUsersUseCase: Symbol.for('ListUsersUseCase'),
  DeleteUserUseCase: Symbol.for('DeleteUserUseCase'),
  CreateProjectUseCase: Symbol.for('CreateProjectUseCase'),
  UpdateProjectUseCase: Symbol.for('UpdateProjectUseCase'),
  GetProjectUseCase: Symbol.for('GetProjectUseCase'),
  ListProjectsUseCase: Symbol.for('ListProjectsUseCase'),
  ChangeProjectStatusUseCase: Symbol.for('ChangeProjectStatusUseCase'),
  DeleteProjectUseCase: Symbol.for('DeleteProjectUseCase'),
  CreateTaskUseCase: Symbol.for('CreateTaskUseCase'),
  UpdateTaskUseCase: Symbol.for('UpdateTaskUseCase'),
  GetTaskUseCase: Symbol.for('GetTaskUseCase'),
  ListTasksUseCase: Symbol.for('ListTasksUseCase'),
  ChangeTaskStatusUseCase: Symbol.for('ChangeTaskStatusUseCase'),
  ReassignTaskUseCase: Symbol.for('ReassignTaskUseCase'),
  LogTimeUseCase: Symbol.for('LogTimeUseCase'),
  DeleteTaskUseCase: Symbol.for('DeleteTaskUseCase'),
  CreateClientUseCase: Symbol.for('CreateClientUseCase'),
  UpdateClientUseCase: Symbol.for('UpdateClientUseCase'),
  GetClientUseCase: Symbol.for('GetClientUseCase'),
  ListClientsUseCase: Symbol.for('ListClientsUseCase'),
  DeleteClientUseCase: Symbol.for('DeleteClientUseCase'),
  CreateSupplierUseCase: Symbol.for('CreateSupplierUseCase'),
  UpdateSupplierUseCase: Symbol.for('UpdateSupplierUseCase'),
  GetSupplierUseCase: Symbol.for('GetSupplierUseCase'),
  ListSuppliersUseCase: Symbol.for('ListSuppliersUseCase'),
  DeleteSupplierUseCase: Symbol.for('DeleteSupplierUseCase'),
  
  // Multi-tenant
  TenantContextService: Symbol.for('TenantContextService'),
  TenantDataIsolationService: Symbol.for('TenantDataIsolationService'),
  TenantConfigurationService: Symbol.for('TenantConfigurationService'),
  TenantMigrationService: Symbol.for('TenantMigrationService'),
  
  // Controllers
  TenantController: Symbol.for('TenantController'),
  UserController: Symbol.for('UserController'),
  ProjectController: Symbol.for('ProjectController'),
  TaskController: Symbol.for('TaskController'),
  ClientController: Symbol.for('ClientController'),
  SupplierController: Symbol.for('SupplierController'),
  ExpenseController: Symbol.for('ExpenseController'),
  InvoiceController: Symbol.for('InvoiceController'),
  PaymentController: Symbol.for('PaymentController'),
  FinancialReportController: Symbol.for('FinancialReportController'),
  TemplateController: Symbol.for('TemplateController'),
  UserSettingsController: Symbol.for('UserSettingsController'),
  TenantSettingsController: Symbol.for('TenantSettingsController'),
  ReportsController: Symbol.for('ReportsController'),
  MonitoringController: Symbol.for('MonitoringController'),
  NotificationController: Symbol.for('NotificationController'),
};
